FROM kortex_jazzy:1.3.4

SHELL ["/bin/bash", "-c"]
WORKDIR ${COLCON_WS}/src/ros2_kortex

RUN git pull origin jazzy

WORKDIR ${COLCON_WS}

RUN vcs import src --skip-existing --input src/ros2_kortex/ros2_kortex.jazzy.repos && \
    vcs import src --skip-existing --input src/ros2_kortex/ros2_kortex-not-released.jazzy.repos && \
    vcs import src --skip-existing --input src/ros2_kortex/simulation.jazzy.repos

RUN apt-get update && rosdep update && \
    rosdep install --ignore-src --from-paths src -y -r && \
    rm -rf /var/lib/apt/lists/* && \
    source /opt/ros/jazzy/setup.bash && \
    colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --parallel-workers 1

CMD ["bash"]